### ISSUE TITLE
Intake ⭐

### ISSUE THREAD

**Issue by tee-bee** [frc2423/2024#4]

**Comment by amorygalili** [comment]
For Saturday (1/20) we should also have simple intake code. Intake will be raised and lowered over the bumper, but for tomorrow only the motor powering the intake wheels will be provided. We should create a subsystem which controls this motor. It should:
- be able to stop
- be able to intake
- be able to outtake 
- provide a default command

**Comment by amorygalili** [comment]
Our intake is very similar to our shoulder/intake from last year. We should consider borrowing a lot of the things we did from last year including using a trapezoidal PID controller: https://docs.wpilib.org/en/stable/docs/software/commandbased/profile-subsystems-commands.html#trapezoidprofilesubsystem
